Calling methods made easy
u32i64/rvk pull request #12
Opened 2020-05-20 15:29 UTC by prostomarkeloff

I have improved `call_method` method and generated functions that they accept generic parameter `T` in that response will be serialized. Also I have updated example.

2020-05-20 16:30 UTC, awaitlink requested changes
I imagine `serde_json` is not needed at all in the examples then?

2020-05-20 16:31 UTC, prostomarkeloff commented
> I imagine `serde_json` is not needed at all in the examples then?

Yes, it is. I have fixed it.

2020-05-20 19:03 UTC, u32i64 commented
You'd probably want to remove it from [README.md lines 31-36](https://github.com/u32i64/rvk/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R31-R36) and [line 74](https://github.com/u32i64/rvk/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R74) as well :wink:

2020-05-20 19:31 UTC, prostomarkeloff commented
> You'd probably want to remove it from [README.md lines 31-36](https://github.com/u32i64/rvk/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R31-R36) and [line 74](https://github.com/u32i64/rvk/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R74) as well wink

Ok, it's done! :)

2020-05-21 08:30 UTC, awaitlink approved these changes
LGTM

2020-05-21 08:34 UTC, merged